server:
  host: "0.0.0.0"
  port: "8080"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  db_name: "subscription_service"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 25
  max_lifetime: 300

logger:
  level: "info"
  development: false
  encoding: "json"