server:
  host: "localhost"
  port: "8080"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 60

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  db_name: "subscription_service_dev"
  ssl_mode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  max_lifetime: 300

logger:
  level: "debug"
  development: true
  encoding: "console"